# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a6d9a5139da2e2c94ab196765cb5f741492abc5e05a5944cd9178fedd017c13e38f2e37c3f5a60329450a5451d88be29f97f687201808de7e12ece7d2bb48896

test:
  secret_key_base: 82241cc48ea2ff1fccc6526ebd3551b002da755ec50ab48ab1bc0dcad2798acc168ea022bc82fcd75b835ca56f87f675a80f3cfd0863e69724cec797be51f211

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
